app:
    schedule:
        rate: 4000
        delay: 4000

spring:
    output:
        ansi:
            enabled: always
    datasource:
        driver-class-name: org.postgresql.Driver

# weitere DB-Einstellungen in der application-dev.yaml, z.B.:
#spring:
#    datasource:
#        url: <jdbc:postgresql://...>
#        username: <username>
#        password: <password>
#
#    jpa:
#        hibernate:
#            ddl-auto: update
#        show-sql: true
#        properties:
#            hibernate:
#                hbm2ddl:
#                    import_files: classpath:/schema.sql
