app:
    schedule:
        rate: 4000
        delay: 4000

spring:
    output:
        ansi:
            enabled: always

    datasource:
        url: jdbc:postgresql://localhost:5432/springtest
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update   # oder create, create-drop je nach Anwendungsfall
        show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
